require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PushMessagesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # PushMessage. As you add validations to PushMessage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PushMessagesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  before(:each) do
      @user = FactoryGirl.create(:admin_user)
      sign_in @user
  end
  describe "GET index" do
    it "assigns all push_messages as @push_messages" do
      push_message = PushMessage.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:push_messages)).to eq([push_message])
    end
  end

  describe "GET show" do
    it "assigns the requested push_message as @push_message" do
      push_message = PushMessage.create! valid_attributes
      get :show, {:id => push_message.to_param}, valid_session
      expect(assigns(:push_message)).to eq(push_message)
    end
  end

  describe "GET new" do
    it "assigns a new push_message as @push_message" do
      get :new, {}, valid_session
      expect(assigns(:push_message)).to be_a_new(PushMessage)
    end
  end

  describe "GET edit" do
    it "assigns the requested push_message as @push_message" do
      push_message = PushMessage.create! valid_attributes
      get :edit, {:id => push_message.to_param}, valid_session
      expect(assigns(:push_message)).to eq(push_message)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PushMessage" do
        expect {
          post :create, {:push_message => valid_attributes}, valid_session
        }.to change(PushMessage, :count).by(1)
      end

      it "assigns a newly created push_message as @push_message" do
        post :create, {:push_message => valid_attributes}, valid_session
        expect(assigns(:push_message)).to be_a(PushMessage)
        expect(assigns(:push_message)).to be_persisted
      end

      it "redirects to the created push_message" do
        post :create, {:push_message => valid_attributes}, valid_session
        expect(response).to redirect_to(PushMessage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved push_message as @push_message" do
        post :create, {:push_message => invalid_attributes}, valid_session
        expect(assigns(:push_message)).to be_a_new(PushMessage)
      end

      it "re-renders the 'new' template" do
        post :create, {:push_message => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested push_message" do
        push_message = PushMessage.create! valid_attributes
        put :update, {:id => push_message.to_param, :push_message => new_attributes}, valid_session
        push_message.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested push_message as @push_message" do
        push_message = PushMessage.create! valid_attributes
        put :update, {:id => push_message.to_param, :push_message => valid_attributes}, valid_session
        expect(assigns(:push_message)).to eq(push_message)
      end

      it "redirects to the push_message" do
        push_message = PushMessage.create! valid_attributes
        put :update, {:id => push_message.to_param, :push_message => valid_attributes}, valid_session
        expect(response).to redirect_to(push_message)
      end
    end

    describe "with invalid params" do
      it "assigns the push_message as @push_message" do
        push_message = PushMessage.create! valid_attributes
        put :update, {:id => push_message.to_param, :push_message => invalid_attributes}, valid_session
        expect(assigns(:push_message)).to eq(push_message)
      end

      it "re-renders the 'edit' template" do
        push_message = PushMessage.create! valid_attributes
        put :update, {:id => push_message.to_param, :push_message => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested push_message" do
      push_message = PushMessage.create! valid_attributes
      expect {
        delete :destroy, {:id => push_message.to_param}, valid_session
      }.to change(PushMessage, :count).by(-1)
    end

    it "redirects to the push_messages list" do
      push_message = PushMessage.create! valid_attributes
      delete :destroy, {:id => push_message.to_param}, valid_session
      expect(response).to redirect_to(push_messages_url)
    end
  end

end
